### ISSUE TITLE
Any version after 2.0.0 crashes on clean fabric server

### ISSUE THREAD

**Issue by IvoryMonster** [Sparkierkan7/thermite_mod#18]
**A 1.20.1 fabric server with only Thermite (version 2.1.0 - 4.1.0) and its dependencies will crash with the error:**
[16:41:04] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'therm'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.0.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.0.jar:?]
Caused by: java.lang.NoSuchFieldError: checkbox
	at me.lortseam.completeconfig.data.BooleanEntry.<init>(BooleanEntry.java:26) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.Entry.create(Entry.java:42) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.EntrySet.lambda$resolve$1(EntrySet.java:31) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at me.lortseam.completeconfig.data.EntrySet.resolve(EntrySet.java:32) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.Parent.resolveContainer(Parent.java:58) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.Parent.resolve(Parent.java:110) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.Config.lambda$new$0(Config.java:51) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.Config.deserialize(Config.java:94) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at me.lortseam.completeconfig.data.Config.load(Config.java:121) ~[completeconfig-base-2.4.0-41ce8135a410a76.jar:?]
	at thermite.therm.ThermMod.onInitialize(ThermMod.java:73) ~[thermite-4.1.0_mc-1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
	... 6 more
**Weirdly, it works fine on quilt, though it may have corrupted certain items or block, but that could have been caused by something else**

**Comment by Cm4nXD** [comment]
I am also getting the same issue. My bet is it has something to do with the fact that quilt uses an older version of fabric api (version 0.90.0 instead of 0.91.3)

**Comment by Sparkierkan7** [comment]
Try using version 0.14.21 of the fabric loader on the server. I tested it and it worked on that version, but same error on anything above it.

It seems to be something to do with CompleteConfig. Versions 2.1.0-4.1.0 all use CompleteConfig, but below 2.1.0 it isn't used.
Also I just found out that CompleteConfig is deprecated and won't update to Minecraft 1.21 so I will be using a different config library in the future.

Also I don't know anything about quilt.

**Comment by Cm4nXD** [comment]
How come this doesn’t crash on clients then?

**Comment by Cm4nXD** [comment]
I cannot use an older version of fabric loader as I have several mods with dependencies on fabric 0.14.24
